server:
  port: 8000
  servlet:
    context-path: /web-market-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: {cipher}AQBJnV9cWPpAdeH3M+St6bjQ2PmTLXAl/6I1nL1PWuWtHZoADegzfVCa6+wTZAN4pK/qRSibVnNafw4YD8W0iz1srdefMte7VUDJDg1XMWux+DDy5zw+sYmAScZSlWB/uLqqyvKg4jz3NtkJ6fU+82z5VVx7T7cfKDmX+Wfp0fvXfXnzhAIfX5vq8qAJMukTm1sGgZbq0a2CuzuCHtcRW8HU3ukFAnkLQHV6DC/eR1FlGXP1XcVsRiMdSYckpH1r9ZUpx/pTPv2OPuHHpASuTWJNwFD2mMCeoznijEVSsVGBfm/uD7DzPdROoK6qbLuc7XNR2QpK9ITJm47OeFRvp105S6CbMkD9W0lkqUQNoeZudj4IHfpRITn/foPBlYbdKNg=
    url: jdbc:postgresql://localhost:5430/beta
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
integrations:
  cart-service:
    url: lb://cart-service/web-market-cart  #  имя приложения в eureka
    connect-timeout: 1000
    read-timeout: 1000
    write-timeout: 1000
    response-timeout: 1000